# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEliminarUnidad():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_eliminarUnidad(self):
    self.driver.get("https://proyecto-ppiv-front.vercel.app/login")
    self.driver.set_window_size(1181, 800)
    self.driver.find_element(By.CSS_SELECTOR, ".login-input-top").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login-input-top").send_keys("germangp62@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".login-input-bottom").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login-input-bottom").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, ".button1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".admincard:nth-child(1) > .admincard__title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".unit-card:nth-child(9) > .unit-card__img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".danger").click()
    self.driver.find_element(By.CSS_SELECTOR, ".modal-buttons > .button1:nth-child(1)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".navbar__logout > svg")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "line")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar__logout > svg").click()
  
