# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAgregarUnidadIncompleto():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_agregarUnidadIncompleto(self):
    self.driver.get("https://proyecto-ppiv-front.vercel.app/login")
    self.driver.set_window_size(1181, 797)
    self.driver.find_element(By.CSS_SELECTOR, ".login-input-top").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login-input-top").send_keys("germangp62@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".login-input-bottom").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login-input-bottom").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, ".button1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".admincard:nth-child(1) > .admincard__title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button1").click()
    self.driver.find_element(By.NAME, "title").click()
    self.driver.find_element(By.NAME, "title").send_keys("pruebaUnidad")
    self.driver.find_element(By.NAME, "description").click()
    self.driver.find_element(By.NAME, "description").send_keys("test de agregado")
    self.driver.find_element(By.NAME, "rooms").click()
    dropdown = self.driver.find_element(By.NAME, "rooms")
    dropdown.find_element(By.XPATH, "//option[. = '3']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".numeric-input:nth-child(1) option:nth-child(3)").click()
    self.driver.find_element(By.NAME, "beds").click()
    dropdown = self.driver.find_element(By.NAME, "beds")
    dropdown.find_element(By.XPATH, "//option[. = '6']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".numeric-input:nth-child(2) option:nth-child(6)").click()
    self.driver.find_element(By.NAME, "bathrooms").click()
    dropdown = self.driver.find_element(By.NAME, "bathrooms")
    dropdown.find_element(By.XPATH, "//option[. = '3']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".numeric-input:nth-child(3) option:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".unit-detail__buttons > .button1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".modal-buttons > .button1:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".modal-buttons > .button1").click()
  
