# Generated by Selenium IDE
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditarUnidad():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_editarUnidad(self):
    self.driver.get("https://proyecto-ppiv-front.vercel.app/login")
    self.driver.set_window_size(1181, 797)
    self.driver.find_element(By.CSS_SELECTOR, ".login-input-top").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login-input-top").send_keys("germangp62@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".login-input-bottom").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, ".button1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".admincard:nth-child(1)").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".unit-card:nth-child(1) > .unit-card__img").click()
    time.sleep(3)
    self.driver.find_element(By.NAME, "rooms").click()
    dropdown = self.driver.find_element(By.NAME, "rooms")
    dropdown.find_element(By.XPATH, "//option[. = '2\\n']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".numeric-input:nth-child(1) option:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".unit-detail__buttons > .button1:nth-child(1)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".unit-detail__buttons > .button1:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".modal-buttons > .button1:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".modal-buttons > .button1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".back-icon").click()
  
